### ISSUE TITLE
API for getting git revision should be more robust.

### ISSUE THREAD

**Issue by mkostoevr** [kolibrios-nextgen/kolibrios-ng#6]
If I understood @Cleverking2003 correctly, currently OS revision is stored in 32-bit integer which only allows to store first 4 bytes of 20-byte git hash.

This should be reworked.

**Comment by turbocat2001** [comment]
Yes, the API needs to be reworked so that the hash is returned as a string. It is also necessary to implement a test for the redesigned system call. The test should output the hash to the debug board.
